version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
            python install.py --vim
            python install.py --shell
            python install.py --tmux

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports
